export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";

export const GET_RECLAMATION = "GET_RECLAMATION";
export const GET_RECLAMATIONS = "GET_RECLAMATIONS";
